---
- name: Inventory RHEL Environment
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  environment:
    OS_USERNAME: "{{ openstack_user }}"
    OS_PASSWORD: "{{ openstack_passwd }}"
    OS_AUTH_URL: "{{ openstack_auth_url }}"
    OS_PROJECT_NAME: "{{ openstack_project }}"
    OS_USER_DOMAIN_NAME: Default
    OS_PROJECT_DOMAIN_NAME: Default
    OS_IDENTITY_API_VERSION: 3
    OS_INTERFACE: public
    OS_CACERT: "{{ cacert }}"

  tasks:
  - import_role:
      name: osp-inventory-instance
    tags: ['inventory']

- name: Debootstrap Instance
  hosts: instance
  become: true
  gather_facts: true
  remote_user: "{{ ssh_user }}"

  tasks:
  - import_role:
      name: sat6-debootstrap
    tags: ['deboostrap']

- name: Remove Client from Satellite
  hosts: master
  become: true
  gather_facts: no
  remote_user: "{{ ssh_user }}"
  environment:
    OS_USERNAME: "{{ openstack_user }}"
    OS_PASSWORD: "{{ openstack_passwd }}"
    OS_AUTH_URL: "{{ openstack_auth_url }}"
    OS_PROJECT_NAME: "{{ openstack_project }}"
    OS_USER_DOMAIN_NAME: Default
    OS_PROJECT_DOMAIN_NAME: Default
    OS_IDENTITY_API_VERSION: 3
    OS_INTERFACE: public
    OS_CACERT: "{{ cacert }}"

  tasks:
  - import_role:
      name: sat6-unregister-client
    tags: ['unregister']

- name: Remove instance
  hosts: localhost
  become: no
  gather_facts: no
  remote_user: "{{ ssh_user }}"
  environment:
    OS_USERNAME: "{{ openstack_user }}"
    OS_PASSWORD: "{{ openstack_passwd }}"
    OS_AUTH_URL: "{{ openstack_auth_url }}"
    OS_PROJECT_NAME: "{{ openstack_project }}"
    OS_USER_DOMAIN_NAME: Default
    OS_PROJECT_DOMAIN_NAME: Default
    OS_IDENTITY_API_VERSION: 3
    OS_INTERFACE: public
    OS_CACERT: "{{ cacert }}"

  tasks:
  - import_role:
      name: osp-delete-instance
    tags: ['delete']
